Day25-TaskManager/TaskManager/Models/Assignment.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TaskManager.Models
{
    public partial class Assignment
    {
        public Assignment()
        {
            WorkTasks = new HashSet<WorkTask>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string AssignedTo { get; set; }

        [InverseProperty("Assignment")]
        public virtual ICollection<WorkTask> WorkTasks { get; set; }
    }
}

Day25-TaskManager/TaskManager/Models/ErrorViewModel.cs
namespace TaskManager.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Day25-TaskManager/TaskManager/Models/TasksDBContext.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;

namespace TaskManager.Models
{
    public partial class TasksDBContext : DbContext
    {
        public TasksDBContext()
        {
        }

        public TasksDBContext(DbContextOptions<TasksDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<WorkTask> WorkTasks { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=SURFACE\\SQLEXPRESS;Initial Catalog=TasksDB;Integrated Security=True;TrustServerCertificate=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<WorkTask>(entity =>
            {
                entity.Property(e => e.Status).HasDefaultValueSql("((0))");

                entity.HasOne(d => d.Assignment)
                    .WithMany(p => p.WorkTasks)
                    .HasForeignKey(d => d.AssignmentId)
                    .HasConstraintName("FK__Tasks__Assignmen__398D8EEE");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

Day25-TaskManager/TaskManager/Models/WorkTask.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TaskManager.Models
{
    public partial class WorkTask
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }
        public bool Status { get; set; }
        public int? AssignmentId { get; set; }

        [ForeignKey("AssignmentId")]
        [InverseProperty("WorkTasks")]
        public virtual Assignment Assignment { get; set; }
    }
}

Day25-TaskManager/TaskManager/Controllers/HomeController.cs
namespace TaskManager.Controllers;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TaskManager.Models;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Day25-TaskManager/TaskManager/Controllers/WorkTaskController.cs
namespace TaskManager.Controllers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TaskManager.Models;
using TaskManager.Services;

public class WorkTaskController : Controller
{
    public IActionResult Index()
    {
        List<WorkTask> tasks = new List<WorkTask>();
        using (TasksDBService service = new TasksDBService())
        {
            tasks = service.GetAllTasks();
        }

        if (tasks.Count > 0)
        {
            return View(tasks);
        }

        return View();
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(WorkTask task)
    {
        if (task == null)
        {
            return BadRequest();
        }

        WorkTask newTask = new WorkTask();
        newTask.Name = task.Name;
        newTask.Description = task.Description;
        newTask.CreatedOn = DateTime.Now;
        newTask.Status = task.Status;
        newTask.Assignment = new Assignment()
        {
            CreatedBy = task.Assignment.CreatedBy,
            AssignedTo = task.Assignment.AssignedTo
        };

        using (TasksDBService service = new TasksDBService())
        {
            service.Create(newTask);
        }

        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
        using (TasksDBContext context = new TasksDBContext())
        {
            if (context.WorkTasks.Any(t => t.Id == id))
            {
                WorkTask task = new WorkTask();
                using (TasksDBService service = new TasksDBService())
                {
                    task = service.GetTask(id);
                }

                return View(task);
            }
        }

        return BadRequest();
    }

    [HttpPost]
    public IActionResult Edit(WorkTask editedTask)
    {
            using (TasksDBService service = new TasksDBService())
            {
                service.Edit(editedTask);
            }

        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Details(int id)
    {
        WorkTask task = new WorkTask();
        using (TasksDBService service = new TasksDBService())
        {
            task = service.GetTask(id);
        }

        if (task == null)
        {
            return BadRequest();
        }

        return View(task);
    }

    [HttpGet]
    public IActionResult Delete(int id)
    {
        using (TasksDBService service = new TasksDBService())
        {
            service.Delete(id);
        }

        return RedirectToAction("Index");
    }
}

Day25-TaskManager/TaskManager/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Day25-TaskManager/TaskManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskManager.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WorkTask" asp-action="Index">WorkTasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TaskManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Day25-TaskManager/TaskManager/Views/WorkTask/Create.cshtml
@model TaskManager.Models.WorkTask
@{
    ViewData["Title"] = "Create new task";
}

<h1>Create new Task</h1>
<div class="row">
    <div clas="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
            </div>
            <div class="form-group">
                <label asp-for="CreatedOn" class="control-label"></label>
                <input asp-for="CreatedOn" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Assignment.CreatedBy" class="control-label"></label>
                <input asp-for="Assignment.CreatedBy" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Assignment.AssignedTo" class="control-label"></label>
                <input asp-for="Assignment.AssignedTo" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Tasks list</a>
</div>

Day25-TaskManager/TaskManager/Views/WorkTask/Details.cshtml
@model TaskManager.Models.WorkTask
@{
    ViewData["Title"] = "Task Details";
}

<h1>Task Details</h1>
<div class="row">
    <div clas="col-md-4">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <p> @Model.Name <p />
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <p> @Model.Description <p />
            </div>
            <div class="form-group">
            <label asp-for="CreatedOn" class="control-label"></label>
            <p>@Model.CreatedOn.ToString("yyyy-MM-ddTHH:mm") <p />
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <p> @Model.Status <p />
            </div>
            <div class="form-group">
                <label asp-for="AssignmentId" class="control-label"></label>
                <p> @Model.AssignmentId <p />
            </div>
            <div class="form-group">
                <label asp-for="Assignment.CreatedBy" class="control-label"></label>
                <p> @Model.Assignment.CreatedBy <p />
            </div>
            <div class="form-group">
                <label asp-for="Assignment.AssignedTo" class="control-label"></label>
                <p> @Model.Assignment.AssignedTo <p />
            </div>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Tasks list</a>
</div>

Day25-TaskManager/TaskManager/Views/WorkTask/Edit.cshtml
@model TaskManager.Models.WorkTask
@{
    ViewData["Title"] = "Edit task";
}

<h1>Edit Task</h1>
<div class="row">
    <div clas="col-md-4">
        <form asp-action="Edit">
            <input type="hidden" asp-for="@Model.Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" value="@Model.Name" />
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" value="@Model.Description" />
            </div>
            <div class="form-group">
                <label asp-for="CreatedOn" class="control-label"></label>
                <input asp-for="CreatedOn" class="form-control" value="@Model.CreatedOn.ToString("yyyy-MM-ddTHH:mm")" />
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" checked="@Model.Status" />
            </div>
            <div class="form-group">
                <label asp-for="Assignment.CreatedBy" class="control-label"></label>
                <input asp-for="Assignment.CreatedBy" class="form-control" value="@Model.Assignment.CreatedBy" />
            </div>
            <div class="form-group">
                <label asp-for="Assignment.AssignedTo" class="control-label"></label>
                <input asp-for="Assignment.AssignedTo" class="form-control" value="@Model.Assignment.AssignedTo" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save changes" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Tasks list</a>
</div>

Day25-TaskManager/TaskManager/Views/WorkTask/Index.cshtml
@model IEnumerable<WorkTask>
@{
    int taskNumber = 1;
}

<h1>Work Tasks</h1>
<p>
    @Html.ActionLink("Create a new task", "Create")
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                #
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Assignment.CreatedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Assignment.AssignedTo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var task in Model)
        {
            <tr>
                <td>
                    @taskNumber
                    @{
                        taskNumber++;
                    }
                </td>
                <td>
                    @task.Name
                </td>
                <td>
                    @task.CreatedOn
                </td>
                <td>
                    @task.Assignment.CreatedBy
                </td>
                <td>
                    @task.Assignment.AssignedTo
                </td>
                <td>
                    @task.Status
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new {id = task.Id})
                    |
                    @Html.ActionLink("Details", "Details", new {id = task.Id})
                    |
                    @Html.ActionLink("Delete", "Delete", new {id = task.Id})
                </td>
            </tr>
        }
    </tbody>
</table>